<a href="https://colab.research.google.com/github/rezadrian01/regressor_model_selection/blob/main/Model_Selection_Excercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [130]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [131]:
dataset = pd.read_csv("Customers_Data.csv")
X1 = dataset.iloc[:, 1:3].values
X2 = dataset.iloc[:, 4:].values
X = np.concatenate((X1, X2), 1)
y = dataset.iloc[:, 3].values

In [132]:
print(X)

[[25 45000 4.5 'North' 12]
 [34 55000 7.0 'South' 18]
 [45 65000 8.0 'West' 22]
 ...
 [54 74000 9.4 'South' 27]
 [32 52000 5.8 'West' 18]
 [31 51000 5.6 'North' 17]]


In [133]:
print(y)

[200 350 500 150 220 480 400 230 600 320 250 520 380 420 590 160 440 300
 510 240 610 170 460 390 430 530 360 280 600 450 350 470 320 230 640 200
 550 300 620 250 440 420 510 380 610 220 480 600 400 170 590 240 500 450
 430 630 360 340 520 640 270 380 600 230 470 480 600 170 550 300 440 420
 510 380 610 250 480 600 400 170 590 240 500 450 430 630 360 340 520 640
 270 380 600 230 470 480 600 170 550 300 440 420 510 380 610 250 480 600
 400 170 590 240 500 450 430 630 360 340 520 640 270 380 600 230 470 480
 600 170 550 300 440 420 510 380 610 250 480 600 400 170 590 240 500 450
 430 630 360 340 520 640 270 380 600 230 470 480 600 170 550 300 440 420
 510 380 610 250 480 600 400 170 590 240 500 450 430 630 360 340 520 640
 270 380 600 230 470 480 600 170 550 300 440 420 510 380 610 250 480 600
 400 170 590 240 500 450 430 630 360 340 520 640 270 380 600 230 470 480
 600 170 550 300 440 420 510 380 610 250 480 600 400 170 590 240 500 450
 430 630 360 340]


In [134]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [3])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[0.0 1.0 0.0 ... 45000 4.5 12]
 [0.0 0.0 1.0 ... 55000 7.0 18]
 [0.0 0.0 0.0 ... 65000 8.0 22]
 ...
 [0.0 0.0 1.0 ... 74000 9.4 27]
 [0.0 0.0 0.0 ... 52000 5.8 18]
 [0.0 1.0 0.0 ... 51000 5.6 17]]


In [135]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [136]:
scores = []

# Multiple Linear Regression

In [137]:
from sklearn.linear_model import LinearRegression
multiple_regressor = LinearRegression()
multiple_regressor.fit(X_train, y_train)

LinearRegression()

In [138]:
from sklearn.metrics import r2_score
y_pred = multiple_regressor.predict(X_test)
result = r2_score(y_test, y_pred)
scores.append({
    "name": "Multiple Linear Regression",
    "score": result
})

# Polynomial Regression

In [139]:
from sklearn.preprocessing import PolynomialFeatures
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
polynomial_regressor = LinearRegression()
polynomial_regressor.fit(X_poly, y_train)

LinearRegression()

In [140]:
y_pred = polynomial_regressor.predict(poly_reg.fit_transform(X_test))
result = r2_score(y_test, y_pred)
scores.append({
    "name": "Polynomial Regression",
    "score": result
})

# Support Vector Regression

In [141]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
support_vector_regressor = SVR(kernel = 'rbf')
sc_X = StandardScaler()
sc_y = StandardScaler()
X_train_SVR = sc_X.fit_transform(X_train)
y_train_SVR = sc_y.fit_transform(y_train.reshape(len(y_train), 1))
support_vector_regressor.fit(X_train_SVR, y_train_SVR)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR()

In [142]:
y_pred = sc_y.inverse_transform(support_vector_regressor.predict(sc_X.transform(X_test)).reshape(-1, 1))
result = r2_score(y_test, y_pred)
scores.append({
    "name": "Support Vector Regression",
    "score": result
})

# Decision Tree Regression

In [143]:
from sklearn.tree import DecisionTreeRegressor
decision_tree_regressor = DecisionTreeRegressor(random_state = 0)
decision_tree_regressor.fit(X_train, y_train)

DecisionTreeRegressor(random_state=0)

In [144]:
y_pred = decision_tree_regressor.predict(X_test)
result = r2_score(y_test, y_pred)
scores.append({
    "name": "Decision Tree Regression",
    "score": result
})

# Random Forest Regression

In [145]:
from sklearn.ensemble import RandomForestRegressor
random_forest_regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
random_forest_regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [146]:
y_pred = random_forest_regressor.predict(X_test)
result = r2_score(y_test, y_pred)
scores.append({
    "name": "Random Forest Regression",
    "score": result
})

# Result

In [150]:
sorted_model_accuracy = sorted(scores, key=lambda score: score['score'], reverse=True)
print(sorted_model_accuracy)

[{'name': 'Random Forest Regression', 'score': 0.9997824480686173}, {'name': 'Decision Tree Regression', 'score': 0.9994515497528165}, {'name': 'Multiple Linear Regression', 'score': 0.9973345281302776}, {'name': 'Polynomial Regression', 'score': 0.9958271093421263}, {'name': 'Support Vector Regression', 'score': 0.9923395005782912}]
